name: mkdocs_deployment

on:
  push:
    branches:
      - gh_pages

jobs:

  build:

    # Grant the job the permission to build the static website using mkdoocs build
    permissions:
      contents: write

    env:
      pip_requirements_path: setup/pip_requirements.txt

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
          cache-dependency-path: ${{ env.pip_requirements_path }}

      - run: pip install -r $pip_requirements_path

      - run: mkdocs build --clean --config-file mkdocs.yaml --site-dir site

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
          retention-days: 1

  deploy:
    needs: build
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4